### ISSUE TITLE
python 3 installtion

### ISSUE THREAD

**Issue by vgoklani** [Supervisor/superlance#118]
Hey - thanks for maintaining this!

How do I install this under python 3? I tried pip:

	Vs-Pro.local vgoklani@~ $ pip install superlance
	Collecting superlance
	  Using cached https://files.pythonhosted.org/packages/14/87/d2b4fe1f9e7f97360e75e125cc03b2216a0ce5092034f203febc3818b7da/superlance-1.0.0-py2.py3-none-any.whl
	Collecting supervisor (from superlance)
	  Using cached https://files.pythonhosted.org/packages/44/60/698e54b4a4a9b956b2d709b4b7b676119c833d811d53ee2500f1b5e96dc3/supervisor-3.3.4.tar.gz
	    Complete output from command python setup.py egg_info:
	    Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.7.0 (default, Jun 28 2018, 07:39:16)
	    [Clang 4.0.1 (tags/RELEASE_401/final)].  Please install using a supported version.

I've been using supervisor with python3 and it's very stable :) but I need crashmail. Thanks!

**Comment by mnaberez** [comment]
```
    Supervisor requires Python 2.4 or later but does not work on any version of Python 3. 
```

The Superlance installation is failing because the `supervisor` package (which is declared as a `superlance` dependency) does not have a PyPI release that supports Python 3.  Since this an issue with Supervisor and not Superlance, I'm going to close this issue.

> I've been using supervisor with python3 and it's very stable :)

It seems that you are running a version of Supervisor from its git repository instead of a PyPI release version.  You can do the same with Superlance until there's a Python 3 compatible release of Supervisor.

**Comment by vgoklani** [comment]
Thanks for the response :)
