### ISSUE TITLE
how to test smscrash

### ISSUE THREAD

**Issue by morfin** [Supervisor/superlance#97]
Hi,

I installed superlance and configured crashsms. crashsms is running:
crashsms                         RUNNING   pid 21683, uptime 0:10:06

This what I added in supervisord.conf:

[eventlistener:crashsms]
command=crashsms --toEmail="test@email_to_sms_gateway.com" --subject="Testing" --smtpHost="smtp.mailgun.org" --userName="postmaster@x.com" --password="xxxxxxx" --fromEmail="info@x.com"
events=PROCESS_STATE

So far no E-mail has been sent. How can I manually cause a PROCESS_STATE change so I can test it out ?

 I stopped one of my processes with: sudo supervisorctl stop worker-1000, but that didn't trigger the event.

Any guidance will be appreciated. Thanks.

**Comment by mnaberez** [comment]
`crashsms` [only sends an alert](https://github.com/Supervisor/superlance/blob/5db5ea80bc37d815ce1fcd5fbcbbdd2c2650c03e/superlance/crashsms.py#L23-L25) when it receives the [`PROCESS_STATE_EXITED`](https://github.com/Supervisor/superlance/blob/5db5ea80bc37d815ce1fcd5fbcbbdd2c2650c03e/superlance/crashsms.py#L70) event, meaning the process has entered the `EXITED` state.  When you stop the process with `supervisorctl stop`, it puts the process into the `STOPPED` state.  Try causing the process to exit another way, e.g. by `kill -9 <pid>` or since Supervisor 3.3.0, `supervisorctl signal 9 <processname>`.  To see detailed messages about what events are being sent to event listeners like `crashsms`, set `loglevel=blat` in the `[supervisord]` section of the config file.

**Comment by morfin** [comment]
Good, I killed it and this is the log (Still not getting any email). 

[worker-64163:worker-1000](19700) exited unexpectedly 2016-10-18 16:29:00,313

2016-10-18 16:29:00,326 DEBG event 5 sent to listener crashsms
2016-10-18 16:29:00,326 BLAT read event caused by <PEventListenerDispatcher at 140586332972960 for <Subprocess at 140586333223392 with name crashsms in state RUNNING> (stdout)>
2016-10-18 16:29:00,326 DEBG 'crashsms' stdout output:
RESULT 2
OKREADY

2016-10-18 16:29:00,327 DEBG crashsms: event was processed
2016-10-18 16:29:00,327 DEBG crashsms: BUSY -> ACKNOWLEDGED
2016-10-18 16:29:00,327 DEBG crashsms: ACKNOWLEDGED -> READY
2016-10-18 16:29:01,329 INFO success: worker-1000 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Any other idea? Is there any log where I can see how crashsms sends the message?

**Comment by mnaberez** [comment]
`crashsms` doesn't have a log file.  It might print some messages to its stderr, which you can see with `supervisorctl tail <processname> stderr` or in the main `supervisord` log if the log level is low enough (like `blat`).  

We use this issue tracker mainly for bugs.  The [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users) is a good place to ask questions installing or using Supervisor and Superlance.
